on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

